[package]
name = "xtask"
version = "0.28.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.40"
bindgen = "0.71.1"
log = "0.4.6"
semver = "1.0.10"
tempfile = "3.4.0"
